version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080"
    volumes:
      - .:/app
    environment:
      - GIN_MODE=release
    deploy:
      replicas: 3  # Количество реплик
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
